services:
  kafka-broker-1:
    image: apache/kafka:3.8.0
    container_name: kafka-broker-1
    environment:
      KAFKA_ENABLE_KRAFT: "true"  # Включает KRAFT вместо Zookeeper
      KAFKA_NODE_ID: 1           # Уникальный ID узла
      KAFKA_PROCESS_ROLES: "broker,controller"  # Роли узла
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094"  # Слушатели
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-broker-1:9092,EXTERNAL://localhost:9094"  # Реклама для клиентов
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093"  # Quorum voters
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"  # Маппинг протоколов
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"  # Слушатель для межброкерной связи
      KAFKA_KRAFT_CLUSTER_ID: "7Dvn0OLMQo-bg4qmCmflVg"  # ID кластера из вашего конфига
    ports:
      - "9094:9094"
    networks:
      - kafka-network

  kafka-broker-2:
    image: apache/kafka:3.8.0
    container_name: kafka-broker-2
    environment:
      KAFKA_ENABLE_KRAFT: "true"
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9095"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-broker-2:9092,EXTERNAL://localhost:9095"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_KRAFT_CLUSTER_ID: "7Dvn0OLMQo-bg4qmCmflVg"
    ports:
      - "9095:9095"
    networks:
      - kafka-network

  kafka-broker-3:
    image: apache/kafka:3.8.0
    container_name: kafka-broker-3
    environment:
      KAFKA_ENABLE_KRAFT: "true"
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9096"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-broker-3:9092,EXTERNAL://localhost:9096"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_KRAFT_CLUSTER_ID: "7Dvn0OLMQo-bg4qmCmflVg"
    ports:
      - "9096:9096"
    networks:
      - kafka-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    environment:
      - KAFKA_CLUSTERS_0_NAME=local-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092
      - KAFKA_CLUSTERS_0_READONLY=false
      - KAFKA_CLUSTERS_0_TOPIC_AUTO_CREATE=true
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
    ports:
      - '8080:8080'
    networks:
      - kafka-network
 

networks:
  kafka-network:
    driver: bridge